version: "3.9"
services:
    mongodb:
        image : mongo
        container_name: mongodb
        environment:
            - PUID=mongo
            - PGID=mongogroup
        volumes:
            - ./database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped